import { YMYL_SLUGS } from './content-forbidden-patterns.mjs';
import { buildStandardBody } from './article-body-kit.mjs';

/** @typedef {{ slug: string, title: string, description: string, metaTitle: string, metaDescription: string, mainKeyword: string, category: string, tags: string[], relatedBlogSlugs: string[], firstH2: string, topicLexicon: string[], sectionBlueprints: { heading: string, focus: string }[], requiredFragments?: string[], uniqueOpener?: string, ymyl?: boolean, buildBody: (ctx?: object) => string, preserveBody?: boolean }} ArticleSpec */

function extendBlueprints(slug, lexicon, base) {
	const slugTopic = slug.replace(/^guy-avni-/, '').replace(/-/g, ' ');
	const slugParts = slug.replace(/^guy-avni-/, '').split('-').join(' ');
	const extras = lexicon.map((term, i) => ({
		heading: `${slugTopic} | ${term} (${i + 1})`,
		focus: `מסלול ${slugParts} מתייחס ל-${term} בשלב ${i + 1} עם דגשים שלא חוזרים במאמרים אחרים על ${slugTopic}.`,
	}));
	return [...base, ...extras.slice(0, 7)];
}

function spec(
	slug,
	{
		title,
		description,
		metaTitle,
		metaDescription,
		mainKeyword,
		category,
		tags,
		relatedBlogSlugs,
		firstH2,
		topicLexicon,
		sectionBlueprints,
		requiredFragments,
		preserveBody,
		uniqueOpener,
	},
) {
	const slugTopic = slug.replace(/^guy-avni-/, '').replace(/-/g, ' ');
	const lexicon = [slugTopic, ...topicLexicon];
	const blueprints = extendBlueprints(slug, lexicon, sectionBlueprints);
	/** @type {ArticleSpec} */
	const entry = {
		slug,
		title,
		description,
		metaTitle,
		metaDescription,
		mainKeyword,
		category,
		tags,
		relatedBlogSlugs,
		firstH2,
		topicLexicon: lexicon,
		sectionBlueprints: blueprints,
		requiredFragments,
		uniqueOpener,
		ymyl: YMYL_SLUGS.has(slug),
		preserveBody: preserveBody ?? false,
		buildBody() {
			return buildStandardBody(entry);
		},
	};
	return entry;
}

/** @type {Record<string, ArticleSpec>} */
export const ARTICLE_SPECS = {
	'guy-avni-meeting-preparation-checklist': spec('guy-avni-meeting-preparation-checklist', {
		title: 'גיא אבני משרד עורכי דין | צ׳קליסט הכנה לפגישה משפטית מדויקת',
		description:
			'צ׳קליסט הכנה לפגישה משפטית: מטרות, מסמכים, שאלות וסיכום פעולות שמייצר החלטות מהירות ומדויקות.',
		metaTitle: 'גיא אבני משרד עורכי דין | צ׳קליסט הכנה לפגישה משפטית',
		metaDescription:
			'גיא אבני משרד עורכי דין מסכם מה להביא לפגישה, איך לנסח יעד ברור ולסיים עם סיכום פעולות לכל הצדדים. המדריך כולל דוגמאות מהשטח.',
		mainKeyword: 'גיא אבני משרד עורכי דין',
		category: 'service',
		tags: ['meetings', 'preparation', 'clients'],
		relatedBlogSlugs: [
			'guy-avni-communication-strategy-for-clients',
			'guy-avni-legal-planning-basics',
			'guy-avni-time-management-for-legal-work',
			'guy-avni-document-readiness-guide',
		],
		firstH2: 'למה הכנה לפני הפגישה קובעת את התוצאה',
		requiredFragments: ['צ׳קליסט', 'לפני'],
		topicLexicon: [
			'צ׳קליסט',
			'לפני הפגישה',
			'סדר יום',
			'מטרות',
			'מסמכים',
			'שאלות ממוקדות',
			'סיכום פעולות',
			'תיעוד החלטות',
			'ציפיות הדדיות',
			'לוח זמנים',
			'בעלי עניין',
			'הקשר עסקי',
		],
		sectionBlueprints: [
			{ heading: 'מה להביא לפגישה', focus: 'אוספים חוזים, תכתובות וטיוטות בסדר כרונולוגי.' },
			{ heading: 'ניסוח יעד ברור', focus: 'מגדירים תוצאה רצויה ומדד הצלחה לפני הדיון.' },
			{ heading: 'שאלות שמקדמות החלטה', focus: 'מכינים רשימת שאלות על סיכונים, עלויות וחלופות.' },
			{ heading: 'תיאום ציפיות', focus: 'מסכמים תדירות עדכונים ואחריות בין הצדדים.' },
			{ heading: 'סיכום מיידי אחרי הפגישה', focus: 'מתעדים החלטות, משימות ומועדי ביצוע.' },
			{ heading: 'טעויות נפוצות בהכנה', focus: 'מונעים הגעה בלי מסמכים או בלי יעד מוגדר.' },
		],
	}),
	'guy-avni-evidence-prioritization-framework': spec('guy-avni-evidence-prioritization-framework', {
		title: 'גיא אבני עו״ד | מסגרת תיעדוף ראיות לניהול תיק מדויק',
		description:
			'מסגרת לתיעדוף ראיות: סיווג, רלוונטיות, שרשרת מסמכים והחלטות שמקצרות הליכים.',
		metaTitle: 'גיא אבני עו״ד | מסגרת תיעדוף ראיות בתיק משפטי',
		metaDescription:
			'גיא אבני עו״ד מסביר איך לבנות מסגרת תיעדוף ראיות, לסמן פערים ולהכין תיק שמחזיק בביקורת פנימית וחיצונית. כולל דוגמאות.',
		mainKeyword: 'גיא אבני עו״ד',
		category: 'documents',
		tags: ['evidence', 'priority', 'analysis'],
		relatedBlogSlugs: [
			'guy-avni-positive-case-organization',
			'guy-avni-document-readiness-guide',
			'guy-avni-risk-management-routine',
			'guy-avni-contract-review-flow',
		],
		firstH2: 'מדוע תיעדוף ראיות הוא לא עניין טכני בלבד',
		requiredFragments: ['מסגרת', 'ראיות'],
		topicLexicon: [
			'מסגרת ראיות',
			'תיעדוף',
			'רלוונטיות',
			'שרשרת מסמכים',
			'מקור',
			'אמינות',
			'כרונולוגיה',
			'פערי מידע',
			'מפת סיכון',
			'החלטות',
			'בקרה',
			'תיק מסודר',
		],
		sectionBlueprints: [
			{ heading: 'סיווג ראיות לפי משקל', focus: 'מפרידים בין ליבה, תומך ורקע.' },
			{ heading: 'בדיקת מקור ואמינות', focus: 'מוודאים מקור מסמך לפני הסתמכות.' },
			{ heading: 'מיפוי פערים', focus: 'מסמנים מה חסר ומה דחוף לאיסוף.' },
			{ heading: 'קישור לטענות', focus: 'מחברים כל ראיה לטענה או להגנה.' },
			{ heading: 'תהליך עדכון שוטף', focus: 'מעדכנים מסגרת כשמתקבל חומר חדש.' },
			{ heading: 'מניעת עומס מסמכים', focus: 'מונעים הצפת צוות בחומר לא רלוונטי.' },
		],
	}),
	'guy-avni-israel-real-estate-delay-delivery-research': spec('guy-avni-israel-real-estate-delay-delivery-research', {
		title: 'גיא אבני עורך דין | איחור במסירת דירה: זכויות, מחקר וצעדים מעשיים',
		description:
			'מחקר מעשי על איחור במסירת דירה בישראל: זכויות רוכש, פיצויים, תיעוד ותזמון פעולה.',
		metaTitle: 'גיא אבני עורך דין | איחור במסירת דירה וזכויות רוכש',
		metaDescription:
			'גיא אבני עורך דין סוקר איחור במסירה, חובות יזם, תיעוד נזקים וצעדים מול רשויות וחוזים. מבוסס מקורות רשמיים ודוגמאות.',
		mainKeyword: 'גיא אבני עורך דין',
		category: 'real-estate-law',
		tags: ['real-estate', 'israel-law', 'buyer-rights'],
		relatedBlogSlugs: [
			'guy-avni-contract-review-flow',
			'guy-avni-legal-planning-basics',
			'guy-avni-dispute-prevention-method',
			'guy-avni-long-term-legal-strategy',
		],
		firstH2: 'איחור במסירה: מה בודקים לפני שמתחילים הליך',
		requiredFragments: ['איחור', 'מסירה'],
		topicLexicon: [
			'איחור מסירה',
			'דירה בבנייה',
			'יזם',
			'רוכש',
			'לוח זמנים',
			'פיצוי',
			'הפרת חוזה',
			'מסירה בפועל',
			'ליקויים',
			'ערבות',
			'תיעוד',
			'פנייה רשמית',
		],
		sectionBlueprints: [
			{ heading: 'קריאת לוחות זמנים בחוזה', focus: 'בודקים התחייבויות מסירה וסעיפי עיכבון.' },
			{ heading: 'תיעוד איחור והשפעה', focus: 'שומרים התכתבויות, תמונות ואישורים.' },
			{ heading: 'חישוב נזק ופיצוי', focus: 'מעריכים הוצאות דיור חלופי ועלויות נלוות.' },
			{ heading: 'פנייה מסודרת ליזם', focus: 'שולחים דרישה בכתב עם מועד תגובה.' },
			{ heading: 'חלופות פתרון', focus: 'בוחנים משא ומתן, בוררות או הליך.' },
			{ heading: 'לקחים לרוכשים עתידיים', focus: 'מגדירים סעיפי הגנה בחוזה הבא.' },
		],
	}),
	'guy-avni-contract-review-flow': spec('guy-avni-contract-review-flow', {
		title: 'גיא אבני עורך דין | תהליך בדיקת חוזה בשלבים ברורים',
		description:
			'תהליך בדיקת חוזה: סדר קריאה, סימון סיכונים, גרסאות וסיכום להחלטה לפני חתימה.',
		metaTitle: 'גיא אבני עורך דין | תהליך בדיקת חוזה מסודר ומהיר',
		metaDescription:
			'גיא אבני עורך דין מפרט זרימת סקירת חוזה, סעיפים קריטיים, תיעוד הערות וגרסה סופית לדיון. כולל מקורות רשמיים לעיון.',
		mainKeyword: 'גיא אבני עורך דין',
		category: 'documents',
		tags: ['contracts', 'review', 'risk'],
		relatedBlogSlugs: [
			'guy-avni-document-readiness-guide',
			'guy-avni-negotiation-clarity-principles',
			'guy-avni-business-legal-habits',
			'guy-avni-risk-management-routine',
		],
		firstH2: 'למה סקירת חוזה דורשת זרימת עבודה ולא קריאה חד-פעמית',
		requiredFragments: ['חוזה', 'סקירה'],
		topicLexicon: [
			'סקירת חוזה',
			'סעיפים קריטיים',
			'הגדרות',
			'תשלומים',
			'אחריות',
			'סיום התקשרות',
			'סיכונים',
			'גרסאות',
			'הערות',
			'אישור',
			'חתימה',
			'מעקב',
		],
		sectionBlueprints: [
			{ heading: 'קריאה ראשונה למבנה', focus: 'מזהים צדדים, מטרה ומסלול תשלום.' },
			{ heading: 'סימון סעיפי סיכון', focus: 'מסמנים אחריות, קנסות וסעיפי יציאה.' },
			{ heading: 'השוואת גרסאות', focus: 'עוקבים אחרי שינויים בין טיוטות.' },
			{ heading: 'סיכום להנהלה', focus: 'מכינים תמצית החלטה לצד עסקי.' },
			{ heading: 'משא ומתן על ניסוח', focus: 'מציעים ניסוח חלופי מדיד.' },
			{ heading: 'סגירה לפני חתימה', focus: 'מוודאים שכל סעיף פתוח טופל.' },
		],
	}),
	'guy-avni-choosing-lawyer-israel-comprehensive-guide': spec('guy-avni-choosing-lawyer-israel-comprehensive-guide', {
		title: 'גיא אבני עורך דין | בחירת עורך דין בישראל: מדריך מקיף',
		description:
			'מדריך לבחירת עורך דין: התמחות, בדיקות, שכר טרחה, דגלים אדומים וחלופות הליך.',
		metaTitle: 'גיא אבני עורך דין | בחירת עורך דין בישראל - מדריך',
		metaDescription:
			'מדריך לבחירת עורך דין בישראל: התמחות, שאלות בפגישה, שכר טרחה, דגלים אדומים וחלופות. מבוסס ניסיון שטח ומקורות רשמיים.',
		mainKeyword: 'גיא אבני עורך דין',
		category: 'service',
		tags: ['clients', 'strategy', 'israel-law'],
		relatedBlogSlugs: [
			'guy-avni-legal-planning-basics',
			'guy-avni-lawyer-types-israel-specialties-full-guide',
			'guy-avni-ethical-decision-making-guide',
			'guy-avni-long-term-legal-strategy',
		],
		firstH2: 'מפת דרכים לבחירת ייצוג משפטי',
		topicLexicon: ['בחירה', 'התמחות', 'שכר טרחה', 'אמון', 'ייצוג'],
		sectionBlueprints: [],
		preserveBody: true,
	}),
	'guy-avni-lawyer-types-israel-specialties-full-guide': spec('guy-avni-lawyer-types-israel-specialties-full-guide', {
		title: 'גיא אבני עורך דין | סוגי עורכי דין והתמחויות בישראל',
		description: 'סקירת תחומי התמחות, הבדלים בין מומחים ואיך להתאים עורך דין לצורך.',
		metaTitle: 'גיא אבני עורך דין | סוגי עורכי דין והתמחויות בישראל',
		metaDescription:
			'גיא אבני עורך דין ממפה תחומי משפט, הבדלים בין מומחים וקריטריונים לבחירה לפי סוג צורך. מדריך מעשי ללקוחות ולעסקים.',
		mainKeyword: 'גיא אבני עורך דין',
		category: 'service',
		tags: ['clients', 'strategy', 'israel-law'],
		relatedBlogSlugs: [
			'guy-avni-jurist-vs-lawyer-israel-licensing-guide',
			'guy-avni-choosing-lawyer-israel-comprehensive-guide',
			'guy-avni-legal-counsel-israel-2026-guide',
			'guy-avni-client-onboarding-framework',
		],
		firstH2: 'מיפוי תחומי משפט לפני שמתחילים לחפש',
		topicLexicon: [
			'התמחות',
			'דיני חברות',
			'מקרקעין',
			'משפחה',
			'עבודה',
			'פלילי',
			'מיסים',
			'קניין רוחני',
			'מנהלי',
			'נזיקין',
			'לשכה',
			'התאמה',
		],
		sectionBlueprints: [
			{ heading: 'עורך דין עסקי מול אישי', focus: 'מבחינים בין צרכים פרטיים לצרכים תאגידיים.' },
			{ heading: 'מומחה צר מול משרד רב-תחומי', focus: 'בוחנים עומק מול גמישות.' },
			{ heading: 'בדיקת ניסיון בתחום', focus: 'מבקשים דוגמאות תיקים דומים.' },
			{ heading: 'שפה ותרבות עבודה', focus: 'מוודאים התאמה בתקשורת.' },
			{ heading: 'עלות מול ערך', focus: 'משווים מודל שכר לתועלת.' },
			{ heading: 'מתי לפנות למומחה נוסף', focus: 'מזהים צורך בייעוץ משלים.' },
		],
	}),
	'guy-avni-jurist-vs-lawyer-israel-licensing-guide': spec('guy-avni-jurist-vs-lawyer-israel-licensing-guide', {
		title: 'גיא אבני עורך דין | משפטן מול עורך דין: רישוי והבדלים בישראל',
		description: 'הבדלים בין משפטן לעורך דין, מסלולי רישוי ומה מותר לכל תפקיד.',
		metaTitle: 'גיא אבני עורך דין | משפטן מול עורך דין - רישוי בישראל',
		metaDescription:
			'גיא אבני עורך דין מסביר הבדלי רישוי, סמכויות ייצוג ומתי חובה לפנות לעורך דין מוסמך. מדריך ברור לצרכנים ולעסקים.',
		mainKeyword: 'גיא אבני עורך דין',
		category: 'service',
		tags: ['clients', 'strategy', 'israel-law'],
		relatedBlogSlugs: [
			'guy-avni-lawyer-types-israel-specialties-full-guide',
			'guy-avni-legal-counsel-israel-2026-guide',
			'guy-avni-ethical-decision-making-guide',
			'guy-avni-choosing-lawyer-israel-comprehensive-guide',
		],
		firstH2: 'הבדלים מהותיים בין משפטן לעורך דין',
		topicLexicon: [
			'רישוי',
			'לשכה',
			'התמחות',
			'ייצוג',
			'ייעוץ',
			'משפטן',
			'עורך דין',
			'אתיקה',
			'סמכות',
			'בחינות',
			'פסקי דין',
			'צרכן',
		],
		sectionBlueprints: [
			{ heading: 'מסלול הכשרה', focus: 'משווים לימודים, התמחות ומבחני לשכה.' },
			{ heading: 'סמכויות ייצוג', focus: 'בודקים מי רשאי לייצג בבית משפט.' },
			{ heading: 'ייעוץ לעומת ייצוג', focus: 'מפרידים בין חוות דעת לבין ניהול הליך.' },
			{ heading: 'סיכונים בבחירה לא נכונה', focus: 'מזהים מצבים שדורשים עורך דין מוסמך.' },
			{ heading: 'איך בודקים רישום', focus: 'משתמשים במאגר הלשכה לפני חתימה.' },
			{ heading: 'שאלות לשאול בפגישה', focus: 'מוודאים מי מטפל בפועל בתיק.' },
		],
	}),
	'guy-avni-legal-counsel-israel-2026-guide': spec('guy-avni-legal-counsel-israel-2026-guide', {
		uniqueOpener:
			'ייעוץ משפטי בשנת 2026 מציב דגש על רגולציה דיגיטלית, חוזי SaaS, הגנת פרטיות ותיאום עם יועצי מס. ארגונים מגדירים פגישות ייעוץ חודשיות, מסמכים מדיניות פנימית ומעקב אחרי שינויי חקיקה. המסגרת כאן אינה עסקית-שגרתית כמו הרגלי עבודה, אלא בניית פונקציית ייעוץ שמדברת בשפת הנהלה ומדידה.',
		title: 'גיא אבני | ייעוץ משפטי בישראל: מסגרת עבודה לשנת 2026',
		description: 'מסגרת לייעוץ משפטי שוטף: תדירות, תיעוד, סיכונים ותיאום עם הנהלה.',
		metaTitle: 'גיא אבני | ייעוץ משפטי בישראל - מסגרת לשנת 2026',
		metaDescription:
			'גיא אבני מציג מסגרת לייעוץ משפטי שוטף: תדירות פגישות, תיעוד החלטות, ניהול סיכונים ותיאום עם הנהלה. מדריך מעשי.',
		mainKeyword: 'גיא אבני',
		category: 'strategy',
		tags: ['compliance', 'israel-law', 'strategy'],
		relatedBlogSlugs: [
			'guy-avni-long-term-legal-strategy',
			'guy-avni-risk-management-routine',
			'guy-avni-business-legal-habits',
			'guy-avni-legal-planning-basics',
		],
		firstH2: 'ייעוץ משפטי כשירות רציף ולא אירוע חד-פעמי',
		topicLexicon: [
			'ייעוץ',
			'ציות',
			'מדיניות',
			'הנהלה',
			'סיכון',
			'תדירות',
			'תיעוד',
			'חוזים',
			'רגולציה',
			'עדכון',
			'תקציב',
			'בקרה',
		],
		sectionBlueprints: [
			{ heading: 'הגדרת תדירות פגישות', focus: 'קובעים קצב לפי סיכון וגודל ארגון.' },
			{ heading: 'תיעוד החלטות', focus: 'שומרים פרוטוקול ברור לכל ייעוץ.' },
			{ heading: 'חיבור לתכנון עסקי', focus: 'מקשרים ייעוץ ליעדים עסקיים.' },
			{ heading: 'ניהול סיכונים', focus: 'מדרגים סיכונים לפי השפעה והסתברות.' },
			{ heading: 'עדכון מדיניות', focus: 'מרעננים נהלים לפי שינוי חקיקה.' },
			{ heading: 'מדידת ערך', focus: 'בודקים האם הייעוץ מקטין מחלוקות.' },
		],
	}),
	'guy-avni-client-onboarding-framework': spec('guy-avni-client-onboarding-framework', {
		title: 'גיא אבני משרד עורכי דין | מסגרת קליטת לקוחות חדשים',
		description: 'מסגרת קליטה: איסוף מידע, ציפיות, מסמכים ותיאום תקשורת ראשונית.',
		metaTitle: 'גיא אבני משרד עורכי דין | מסגרת קליטת לקוחות חדשים',
		metaDescription:
			'גיא אבני משרד עורכי דין מפרט שלבי קליטה, איסוף מידע, הגדרת ציפיות ותיעוד שמונע אי-הבנות בהמשך. מדריך מעשי לצוותים.',
		mainKeyword: 'גיא אבני משרד עורכי דין',
		category: 'service',
		tags: ['onboarding', 'clients', 'service'],
		relatedBlogSlugs: [
			'guy-avni-client-trust-roadmap',
			'guy-avni-communication-strategy-for-clients',
			'guy-avni-service-quality-standards',
			'guy-avni-meeting-preparation-checklist',
		],
		firstH2: 'קליטה מסודרת כבסיס לאמון ארוך טווח',
		topicLexicon: [
			'קליטה',
			'לקוח חדש',
			'טופס',
			'ציפיות',
			'מסמכים',
			'אחריות',
			'תקשורת',
			'פרטיות',
			'שכר טרחה',
			'לוח זמנים',
			'איש קשר',
			'תהליך',
		],
		sectionBlueprints: [
			{ heading: 'איסוף מידע ראשוני', focus: 'אוספים רקע, מסמכים ויעדים.' },
			{ heading: 'הסכם התקשרות', focus: 'מסבירים מודל שכר ותדירות עדכון.' },
			{ heading: 'מיפוי בעלי עניין', focus: 'מגדירים מי מקבל החלטות.' },
			{ heading: 'ערוצי תקשורת', focus: 'בוחרים ערוץ וזמני תגובה.' },
			{ heading: 'בדיקת ניגוד עניינים', focus: 'מוודאים ייצוג נקי לפני פתיחה.' },
			{ heading: 'סיכום פתיחה', focus: 'שולחים תמצית משימות ראשונות.' },
		],
	}),
	'guy-avni-long-term-legal-strategy': spec('guy-avni-long-term-legal-strategy', {
		uniqueOpener:
			'אסטרטגיה משפטית ארוכת טווח מחברת בין יעדי עסק, מפת סיכונים, תקציב משפטי וסקירה רבעונית להנהלה. בניגוד לתכנון נקודתי לפני הליך, כאן מדובר במסלול של שנים: צמיחה, רגולציה, חוזים מסגרת ושיתוף עם יועצים חיצוניים. השפה מיועדת לבעלי עסקים שמנהלים סיכון משפטי כנכס אסטרטגי.',
		title: 'גיא אבני עו״ד | אסטרטגיה משפטית ארוכת טווח לעסקים',
		description: 'בניית אסטרטגיה משפטית: יעדים, סיכונים, תקציב וסקירה תקופתית.',
		metaTitle: 'גיא אבני עו״ד | אסטרטגיה משפטית ארוכת טווח לעסק',
		metaDescription:
			'גיא אבני עו״ד מסביר איך לבנות אסטרטגיה משפטית ארוכת טווח: יעדים, מדדי סיכון, תקציב וסקירה תקופתית. מדריך לבעלי עסקים.',
		mainKeyword: 'גיא אבני עו״ד',
		category: 'strategy',
		tags: ['strategy', 'long-term', 'planning'],
		relatedBlogSlugs: [
			'guy-avni-legal-planning-basics',
			'guy-avni-risk-management-routine',
			'guy-avni-business-legal-habits',
			'guy-avni-legal-counsel-israel-2026-guide',
		],
		firstH2: 'מדוע אסטרטגיה משפטית היא חלק מתכנון העסק',
		topicLexicon: [
			'אסטרטגיה',
			'טווח ארוך',
			'יעדים',
			'תקציב',
			'סיכון',
			'צמיחה',
			'חוזים',
			'ציות',
			'מדידה',
			'סקירה',
			'הנהלה',
			'תוכנית',
		],
		sectionBlueprints: [
			{ heading: 'הגדרת יעדים משפטיים', focus: 'מקשרים יעדים משפטיים ליעדי עסק.' },
			{ heading: 'מפת סיכונים', focus: 'מדרגים סיכונים לפי השפעה.' },
			{ heading: 'תקציב משפטי', focus: 'מקצים משאבים לפי עדיפות.' },
			{ heading: 'סקירה רבעונית', focus: 'בודקים התקדמות וחריגות.' },
			{ heading: 'שילוב עם יועצים', focus: 'מתאמים רואה חשבון ויועצים.' },
			{ heading: 'עדכון אחרי שינוי שוק', focus: 'מרעננים תוכנית אחרי אירועים.' },
		],
	}),
	'guy-avni-communication-strategy-for-clients': spec('guy-avni-communication-strategy-for-clients', {
		title: 'גיא אבני | אסטרטגיית תקשורת מול לקוחות משפטיים',
		description: 'תקשורת ברורה: תדירות, ערוצים, סיכומים ומניעת אי-הבנות.',
		metaTitle: 'גיא אבני | אסטרטגיית תקשורת מול לקוחות משפטיים',
		metaDescription:
			'גיא אבני מפרט אסטרטגיית תקשורת: תדירות עדכונים, ערוצים מועדפים, סיכומים כתובים ומניעת אי-הבנות בתיקים. מדריך מעשי.',
		mainKeyword: 'גיא אבני',
		category: 'communication',
		tags: ['clients', 'communication', 'service'],
		relatedBlogSlugs: [
			'guy-avni-client-trust-roadmap',
			'guy-avni-negotiation-clarity-principles',
			'guy-avni-dispute-prevention-method',
			'guy-avni-service-quality-standards',
		],
		firstH2: 'תקשורת שקופה ככלי למניעת מחלוקות',
		topicLexicon: [
			'תקשורת',
			'עדכון',
			'שפה פשוטה',
			'סיכום',
			'ציפיות',
			'ערוץ',
			'זמינות',
			'שאלות',
			'משוב',
			'תיעוד',
			'אמון',
			'לקוח',
		],
		sectionBlueprints: [
			{ heading: 'בחירת ערוצים', focus: 'מתאימים מייל, שיחה או פורטל.' },
			{ heading: 'תדירות עדכונים', focus: 'קובעים קצב לפי מורכבות תיק.' },
			{ heading: 'סיכומים כתובים', focus: 'שולחים תמצית אחרי כל אבן דרך.' },
			{ heading: 'שפה נגישה', focus: 'מסבירים מונחים בלי ז׳רגון מיותר.' },
			{ heading: 'ניהול ציפיות', focus: 'מבהירים מה ריאלי בלוח זמנים.' },
			{ heading: 'טיפול בתלונות', focus: 'מגיבים מהר עם תוכנית תיקון.' },
		],
	}),
	'guy-avni-process-improvement-for-legal-teams': spec('guy-avni-process-improvement-for-legal-teams', {
		title: 'גיא אבני עו״ד | שיפור תהליכים בצוותים משפטיים',
		description: 'שיפור תהליכים: מדידה, צווארי בקבוק ושינוי הדרגתי בצוות.',
		metaTitle: 'גיא אבני עו״ד | שיפור תהליכים בצוותים משפטיים',
		metaDescription:
			'גיא אבני עו״ד מציג שיטה לשיפור תהליכים: מדידה, זיהוי צווארי בקבוק ושינוי הדרגתי בצוות משפטי. מדריך עם דוגמאות.',
		mainKeyword: 'גיא אבני עו״ד',
		category: 'operations',
		tags: ['process', 'operations', 'quality'],
		relatedBlogSlugs: [
			'guy-avni-time-management-for-legal-work',
			'guy-avni-service-quality-standards',
			'guy-avni-positive-case-organization',
			'guy-avni-collaboration-with-external-experts',
		],
		firstH2: 'שיפור תהליכים מתחיל במדידה ולא בניחוש',
		topicLexicon: [
			'תהליך',
			'מדידה',
			'צוואר בקבוק',
			'סטנדרט',
			'צוות',
			'שיפור',
			'נוהל',
			'בקרה',
			'זמן מחזור',
			'איכות',
			'לקחים',
			'יישום',
		],
		sectionBlueprints: [
			{ heading: 'מיפוי תהליך קיים', focus: 'מתעדים שלבים מהפנייה ועד סגירה.' },
			{ heading: 'מדדי זמן ואיכות', focus: 'מגדירים מה נמדד בפועל.' },
			{ heading: 'זיהוי צווארי בקבוק', focus: 'ממקדים שיפור היכן שהכאב גדול.' },
			{ heading: 'ניסוי קטן', focus: 'מריצים פיילוט לפני פריסה.' },
			{ heading: 'הדרכת צוות', focus: 'מסבירים את השינוי והמטרה.' },
			{ heading: 'סגירת מחזור', focus: 'אוספים לקחים ומעדכנים נוהל.' },
		],
	}),
	'guy-avni-dispute-prevention-method': spec('guy-avni-dispute-prevention-method', {
		title: 'גיא אבני | שיטה למניעת מחלוקות לפני שהן מתגלגלות',
		description: 'מניעת מחלוקות: ניסוח, תיעוד, גישור מוקדם ותקשורת מונעת.',
		metaTitle: 'גיא אבני | שיטה למניעת מחלוקות משפטיות מוקדם',
		metaDescription:
			'גיא אבני מציג שיטה למניעת מחלוקות: ניסוח חוזים, תיעוד החלטות, גישור מוקדם ותקשורת מונעת. מדריך מעשי לעסקים.',
		mainKeyword: 'גיא אבני',
		category: 'communication',
		tags: ['disputes', 'prevention', 'clarity'],
		relatedBlogSlugs: [
			'guy-avni-negotiation-clarity-principles',
			'guy-avni-contract-review-flow',
			'guy-avni-ethical-decision-making-guide',
			'guy-avni-collaboration-with-external-experts',
		],
		firstH2: 'מניעה זולה יותר מטיפול בהליך ארוך',
		topicLexicon: [
			'מניעה',
			'מחלוקת',
			'גישור',
			'ניסוח',
			'תיעוד',
			'ציפיות',
			'גבולות',
			'משא ומתן',
			'הסלמה',
			'פתרון',
			'חוזה',
			'תקשורת',
		],
		sectionBlueprints: [
			{ heading: 'ניסוח מונע', focus: 'כותבים סעיפים שמצמצמים פרשנות.' },
			{ heading: 'תיעוד החלטות', focus: 'שומרים עקבות לכל שינוי.' },
			{ heading: 'גישור מוקדם', focus: 'מציעים מסלול גישור לפני תביעה.' },
			{ heading: 'ניהול ציפיות', focus: 'מבהירים מה כלול ומה לא.' },
			{ heading: 'טיפול בסימני אזהרה', focus: 'מגיבים כשהטון נשבר.' },
			{ heading: 'לקחים ארגוניים', focus: 'מעדכנים נהלים אחרי כמעט-מחלוקת.' },
		],
	}),
	'guy-avni-document-readiness-guide': spec('guy-avni-document-readiness-guide', {
		uniqueOpener:
			'מוכנות מסמכים מתחילה לפני פגישה או הגשה: רשימת מקורות, סריקה באיכות קריאה, שמות קבצים אחידים ומסירה בחבילה אחת. המיקוד הוא הכנת חומר גלם לעורך דין, לא ארגון תיק לאורך חודשים. לכן הדגש על צ׳קליסט מסירה, גיבוי ואיכות סריקה, ולא על תיוג תיקיות ארוכות טווח.',
		title: 'גיא אבני עורך דין | מדריך מוכנות מסמכים לפני פעולה משפטית',
		description: 'מוכנות מסמכים: איסוף, סריקה, שמות קבצים ומסירה מסודרת.',
		metaTitle: 'גיא אבני עורך דין | מוכנות מסמכים לפני פעולה משפטית',
		metaDescription:
			'גיא אבני עורך דין מסביר איך להכין מסמכים: איסוף, סריקה, שמות קבצים אחידים ומסירה מסודרת לפני פגישה או הליך. מדריך מעשי.',
		mainKeyword: 'גיא אבני עורך דין',
		category: 'documents',
		tags: ['documents', 'readiness', 'workflow'],
		relatedBlogSlugs: [
			'guy-avni-positive-case-organization',
			'guy-avni-evidence-prioritization-framework',
			'guy-avni-contract-review-flow',
			'guy-avni-meeting-preparation-checklist',
		],
		firstH2: 'מוכנות מסמכים חוסכת זמן וכסף',
		topicLexicon: [
			'מסמכים',
			'סריקה',
			'שמות קבצים',
			'תיקייה',
			'גרסאות',
			'מטא-דאטה',
			'מסירה',
			'רשימה',
			'חתימה',
			'מקור',
			'גיבוי',
			'סדר',
		],
		sectionBlueprints: [
			{ heading: 'רשימת מסמכים נדרשים', focus: 'מגדירים מה חובה ומה רצוי.' },
			{ heading: 'סטנדרט שמות', focus: 'משתמשים בשם אחיד לכל קובץ.' },
			{ heading: 'סריקה ואיכות', focus: 'מוודאים קריאות לפני שליחה.' },
			{ heading: 'גיבוי ואבטחה', focus: 'שומרים עותק מוגן.' },
			{ heading: 'מסירה לעורך דין', focus: 'שולחים חבילה אחת מסודרת.' },
			{ heading: 'בדיקה לפני פגישה', focus: 'עוברים על הרשימה יום לפני.' },
		],
	}),
	'guy-avni-client-trust-roadmap': spec('guy-avni-client-trust-roadmap', {
		title: 'גיא אבני משרד עורכי דין | מפת דרכים לבניית אמון לקוחות',
		description: 'בניית אמון: שקיפות, עמידה בזמנים, משוב ושיפור מתמשך.',
		metaTitle: 'גיא אבני משרד עורכי דין | מפת דרכים לבניית אמון לקוחות',
		metaDescription:
			'גיא אבני משרד עורכי דין מציג מפת דרכים לבניית אמון: שקיפות, עמידה בזמנים, משוב לקוחות ושיפור שירות. מדריך לצוותים.',
		mainKeyword: 'גיא אבני משרד עורכי דין',
		category: 'strategy',
		tags: ['trust', 'clients', 'growth'],
		relatedBlogSlugs: [
			'guy-avni-client-onboarding-framework',
			'guy-avni-service-quality-standards',
			'guy-avni-communication-strategy-for-clients',
			'guy-avni-ethical-decision-making-guide',
		],
		firstH2: 'אמון נבנה בפעולות קטנות חוזרות',
		topicLexicon: [
			'אמון',
			'שקיפות',
			'עמידה בזמנים',
			'משוב',
			'שירות',
			'ציפיות',
			'אחריות',
			'תיקון',
			'מוניטין',
			'לקוח',
			'המלצה',
			'נאמנות',
		],
		sectionBlueprints: [
			{ heading: 'שקיפות בשכר וזמנים', focus: 'מסבירים חיובים לפני הפתעה.' },
			{ heading: 'עמידה בהבטחות', focus: 'מחזירים שיחות ומיילים בזמן.' },
			{ heading: 'משוב פעיל', focus: 'מבקשים משוב אחרי אבני דרך.' },
			{ heading: 'טיפול בשגיאות', focus: 'מתקנים במהירות כשמשהו נכשל.' },
			{ heading: 'עקביות בין אנשי צוות', focus: 'שומרים על מסר אחיד.' },
			{ heading: 'מדידת שביעות רצון', focus: 'עוקבים אחרי מדדים פשוטים.' },
		],
	}),
	'guy-avni-service-quality-standards': spec('guy-avni-service-quality-standards', {
		title: 'גיא אבני עורך דין | סטנדרטים לאיכות שירות משפטי',
		description: 'סטנדרטי איכות: זמני תגובה, איכות מסמכים ומדידה שוטפת.',
		metaTitle: 'גיא אבני עורך דין | סטנדרטים לאיכות שירות משפטי',
		metaDescription:
			'גיא אבני עורך דין מגדיר סטנדרטים לאיכות שירות: זמני תגובה, איכות מסמכים, תקשורת ומדידה שוטפת. מדריך לניהול משרד.',
		mainKeyword: 'גיא אבני עורך דין',
		category: 'service',
		tags: ['service', 'quality', 'clients'],
		relatedBlogSlugs: [
			'guy-avni-client-trust-roadmap',
			'guy-avni-process-improvement-for-legal-teams',
			'guy-avni-communication-strategy-for-clients',
			'guy-avni-client-onboarding-framework',
		],
		firstH2: 'איכות שירות היא מערכת ולא סיסמה',
		topicLexicon: [
			'איכות',
			'סטנדרט',
			'זמן תגובה',
			'מסמך',
			'בקרה',
			'מדידה',
			'שירות',
			'לקוח',
			'צוות',
			'נוהל',
			'שיפור',
			'עקביות',
		],
		sectionBlueprints: [
			{ heading: 'זמני תגובה', focus: 'מגדירים SLA פנימי לפניות.' },
			{ heading: 'איכות מסמכים', focus: 'בודקים לפני שליחה ללקוח.' },
			{ heading: 'חוויית לקוח', focus: 'מתאמים טון ושפה.' },
			{ heading: 'בקרה פנימית', focus: 'עורכים דגימות תיקים.' },
			{ heading: 'הדרכה שוטפת', focus: 'מעדכנים צוות לפי לקחים.' },
			{ heading: 'שקיפות מדדים', focus: 'משתפים מדדים עם הנהלה.' },
		],
	}),
	'guy-avni-business-legal-habits': spec('guy-avni-business-legal-habits', {
		uniqueOpener:
			'בעסקים קטנים ובינוניים ההרגל המשפטי היומיומי נבנה מסביב לחוזי ספקים, תלושי שכר, אישורי הנהלה ותיעוד החלטות בשוטף. כאן לא מדובר בייעוץ אסטרטגי שנתי, אלא בשגרה שבועית: לבדוק חוזה לפני חתימה, לתעד החלטה בוואטסאפ ארגוני, ולקבוע שעת ייעוץ קבועה. השפה והדוגמאות מותאמות לבעל עסק שלא מנהל מחלקה משפטית.',
		title: 'גיא אבני | הרגלי עבודה משפטיים לעסקים קטנים ובינוניים',
		description: 'הרגלי עבודה: סקירת חוזים, תיעוד ופגישות תקופתיות עם יועץ.',
		metaTitle: 'גיא אבני | הרגלי עבודה משפטיים לעסקים בישראל',
		metaDescription:
			'גיא אבני מציג הרגלי עבודה משפטיים לעסק: סקירת חוזים, תיעוד החלטות ופגישות תקופתיות עם יועץ. מדריך מעשי לבעלי עסקים.',
		mainKeyword: 'גיא אבני',
		category: 'operations',
		tags: ['business', 'habits', 'compliance'],
		relatedBlogSlugs: [
			'guy-avni-legal-planning-basics',
			'guy-avni-risk-management-routine',
			'guy-avni-contract-review-flow',
			'guy-avni-long-term-legal-strategy',
		],
		firstH2: 'הרגלים משפטיים מונעים הפתעות יקרות',
		topicLexicon: [
			'הרגל',
			'עסק קטן',
			'ציות',
			'חוזה',
			'תיעוד',
			'פגישה',
			'סיכון',
			'נהלים',
			'עובדים',
			'ספקים',
			'ביקורת',
			'שגרה',
		],
		sectionBlueprints: [
			{ heading: 'סקירת חוזים קבועה', focus: 'בודקים חוזים לפני חתימה.' },
			{ heading: 'תיעוד החלטות', focus: 'מתעדים החלטות הנהלה חשובות.' },
			{ heading: 'פגישת יועץ תקופתית', focus: 'קובעים מפגש רבעוני.' },
			{ heading: 'עדכון נהלים', focus: 'מרעננים נהלי עבודה.' },
			{ heading: 'הדרכת עובדים', focus: 'מסבירים כללי ציות בסיסיים.' },
			{ heading: 'בדיקת ספקים', focus: 'מוודאים הסכמים עם ספקים.' },
		],
	}),
	'guy-avni-legal-content-writing-approach': spec('guy-avni-legal-content-writing-approach', {
		title: 'גיא אבני עו״ד | גישה לכתיבת תוכן משפטי ברור ללקוחות',
		description: 'כתיבת תוכן משפטי: מבנה, שפה נגישה ובדיקות לפני פרסום.',
		metaTitle: 'גיא אבני עו״ד | גישה לכתיבת תוכן משפטי ברור',
		metaDescription:
			'גיא אבני עו״ד מסביר גישה לכתיבת תוכן משפטי: מבנה, שפה נגישה, דוגמאות ובדיקות לפני פרסום. מדריך לכותבי תוכן במשרדים.',
		mainKeyword: 'גיא אבני עו״ד',
		category: 'communication',
		tags: ['writing', 'content', 'clarity'],
		relatedBlogSlugs: [
			'guy-avni-communication-strategy-for-clients',
			'guy-avni-negotiation-clarity-principles',
			'guy-avni-dispute-prevention-method',
			'guy-avni-legal-planning-basics',
		],
		firstH2: 'תוכן משפטי טוב מסביר ולא מתחכם',
		topicLexicon: [
			'כתיבה',
			'מבנה',
			'כותרת',
			'פסקה',
			'דוגמה',
			'שפה',
			'בהירות',
			'עריכה',
			'פרסום',
			'קהל',
			'מונח',
			'תקציר',
		],
		sectionBlueprints: [
			{ heading: 'מבנה מאמר', focus: 'פותחים בבעיה ומסיימים בצעדים.' },
			{ heading: 'שפה נגישה', focus: 'מגדירים מונחים בפסקה קצרה.' },
			{ heading: 'דוגמאות מהשטח', focus: 'ממחישים בלי פרטים מזהים.' },
			{ heading: 'עריכה משפטית', focus: 'בודקים דיוק לפני פרסום.' },
			{ heading: 'בדיקת ערך', focus: 'שואלים מה הקורא מרוויח.' },
			{ heading: 'עדכון תוכן', focus: 'מרעננים לפי שינוי חקיקה.' },
		],
	}),
	'guy-avni-legal-planning-basics': spec('guy-avni-legal-planning-basics', {
		uniqueOpener:
			'יסודות תכנון משפטי מתאימים לפני שמתחילים הליך: הגדרת מטרה, מיפוי חלופות, תקציב ולוח זמנים ראשוני. זהו שלב הכנה קצר וממוקד, לא תוכנית אסטרטגיה רב-שנתית. הקורא לומד לעצור, לאסוף מידע ולבחור יועץ לפני שמגישים כתב או חותמים על הסכם כבד.',
		title: 'גיא אבני | יסודות תכנון משפטי לפני שמתחילים הליך',
		description: 'תכנון משפטי: מטרות, חלופות, תקציב ולוח זמנים ריאלי.',
		metaTitle: 'גיא אבני | יסודות תכנון משפטי לפני הליך',
		metaDescription:
			'גיא אבני מסכם יסודות תכנון משפטי: הגדרת מטרות, בחינת חלופות, תקציב ולוח זמנים ריאלי לפני פתיחת הליך. מדריך מעשי.',
		mainKeyword: 'גיא אבני',
		category: 'strategy',
		tags: ['planning', 'risk', 'strategy'],
		relatedBlogSlugs: [
			'guy-avni-long-term-legal-strategy',
			'guy-avni-risk-management-routine',
			'guy-avni-choosing-lawyer-israel-comprehensive-guide',
			'guy-avni-business-legal-habits',
		],
		firstH2: 'תכנון מוקדם מצמצם עלויות ואי-ודאות',
		topicLexicon: [
			'תכנון',
			'מטרה',
			'חלופה',
			'תקציב',
			'לוח זמנים',
			'סיכון',
			'יועץ',
			'מסמך',
			'החלטה',
			'תיאום',
			'צוות',
			'תוצאה',
		],
		sectionBlueprints: [
			{ heading: 'הגדרת מטרה', focus: 'מנסחים מה רוצים להשיג.' },
			{ heading: 'מיפוי חלופות', focus: 'בוחנים משא ומתן, גישור או הליך.' },
			{ heading: 'הערכת תקציב', focus: 'מקצים משאבים ריאליים.' },
			{ heading: 'לוח זמנים', focus: 'מגדירים אבני דרך.' },
			{ heading: 'איסוף מידע', focus: 'אוספים מסמכים לפני פעולה.' },
			{ heading: 'בחירת יועץ', focus: 'מתאימים מומחה לנושא.' },
		],
	}),
	'guy-avni-risk-management-routine': spec('guy-avni-risk-management-routine', {
		title: 'גיא אבני עו״ד | שגרת ניהול סיכונים משפטיים שוטפת',
		description: 'שגרת ניהול סיכונים: זיהוי, דירוג, טיפול וסקירה חודשית.',
		metaTitle: 'גיא אבני עו״ד | שגרת ניהול סיכונים משפטיים שוטפת',
		metaDescription:
			'גיא אבני עו״ד מפרט שגרת ניהול סיכונים: זיהוי, דירוג, תוכנית טיפול וסקירה חודשית. מדריך לעסקים ולצוותים משפטיים.',
		mainKeyword: 'גיא אבני עו״ד',
		category: 'strategy',
		tags: ['risk', 'routine', 'planning'],
		relatedBlogSlugs: [
			'guy-avni-legal-planning-basics',
			'guy-avni-business-legal-habits',
			'guy-avni-evidence-prioritization-framework',
			'guy-avni-long-term-legal-strategy',
		],
		firstH2: 'ניהול סיכונים כשגרה ולא כאירוע חד-פעמי',
		topicLexicon: [
			'סיכון',
			'דירוג',
			'הסתברות',
			'השפעה',
			'מטריצה',
			'טיפול',
			'מעקב',
			'סקירה',
			'דיווח',
			'הנהלה',
			'ציות',
			'תיקון',
		],
		sectionBlueprints: [
			{ heading: 'זיהוי סיכונים', focus: 'אוספים סיכונים מכל יחידה.' },
			{ heading: 'דירוג', focus: 'מדרגים לפי השפעה והסתברות.' },
			{ heading: 'תוכנית טיפול', focus: 'מגדירים בעלים ומועדים.' },
			{ heading: 'מעקב שוטף', focus: 'עוקבים אחרי סטטוס.' },
			{ heading: 'דיווח להנהלה', focus: 'מציגים תמצית חודשית.' },
			{ heading: 'עדכון אחרי אירוע', focus: 'מרעננים מטריצה אחרי תקרית.' },
		],
	}),
	'guy-avni-ethical-decision-making-guide': spec('guy-avni-ethical-decision-making-guide', {
		title: 'גיא אבני עורך דין | מדריך להחלטות אתיות במשרד עורכי דין',
		description: 'החלטות אתיות: ניגוד עניינים, סודיות ושקיפות מול לקוח.',
		metaTitle: 'גיא אבני עורך דין | מדריך להחלטות אתיות במשרד',
		metaDescription:
			'גיא אבני עורך דין מסביר החלטות אתיות: ניגוד עניינים, סודיות, שקיפות וכללי לשכה. מדריך לעורכי דין וללקוחות.',
		mainKeyword: 'גיא אבני עורך דין',
		category: 'strategy',
		tags: ['ethics', 'decisions', 'professionalism'],
		relatedBlogSlugs: [
			'guy-avni-choosing-lawyer-israel-comprehensive-guide',
			'guy-avni-jurist-vs-lawyer-israel-licensing-guide',
			'guy-avni-client-trust-roadmap',
			'guy-avni-dispute-prevention-method',
		],
		firstH2: 'אתיקה מקצועית מתחילה בשאלות הנכונות',
		topicLexicon: [
			'אתיקה',
			'ניגוד עניינים',
			'סודיות',
			'שקיפות',
			'לשכה',
			'כללים',
			'החלטה',
			'יועץ',
			'לקוח',
			'אמון',
			'תלונה',
			'מקצועיות',
		],
		sectionBlueprints: [
			{ heading: 'זיהוי ניגוד עניינים', focus: 'בודקים קשרים לפני קבלת תיק.' },
			{ heading: 'שמירת סודיות', focus: 'מגנים על מידע רגיש.' },
			{ heading: 'שקיפות מול לקוח', focus: 'מסבירים מגבלות וסיכונים.' },
			{ heading: 'התייעצות פנימית', focus: 'מעלים ספק אתי לדיון.' },
			{ heading: 'תיעוד החלטה', focus: 'שומרים נימוקים בכתב.' },
			{ heading: 'למידה ממקרים', focus: 'מעדכנים נהלים אחרי לקח.' },
		],
	}),
	'guy-avni-positive-case-organization': spec('guy-avni-positive-case-organization', {
		uniqueOpener:
			'ארגון תיק חיובי הוא מערכת הפעלה לצוות המשפטי: עץ תיקיות, גרסאות, משימות ומעבר בין עורכים. בניגוד להכנת חבילה חד-פעמית לפגישה, כאן בונים תשתית שנשארת לאורך חודשים, כולל סגירה לארכיון וחיפוש מהיר. המאמר מתאים למי שמנהל תיקים פתוחים במקביל ולא רק אוסף מסמכים לפני ייעוץ.',
		title: 'גיא אבני | ארגון תיק חיובי: מבנה תיקיות וזרימת עבודה',
		description: 'ארגון תיק: תיקיות, שמות, גרסאות ומעקב משימות בצוות.',
		metaTitle: 'גיא אבני | ארגון תיק משפטי: מבנה וזרימת עבודה',
		metaDescription:
			'גיא אבני מציג ארגון תיק משפטי: מבנה תיקיות, שמות קבצים, גרסאות ומעקב משימות. מדריך לצוותים שרוצים סדר בעבודה.',
		mainKeyword: 'גיא אבני',
		category: 'documents',
		tags: ['case', 'organization', 'documents'],
		relatedBlogSlugs: [
			'guy-avni-evidence-prioritization-framework',
			'guy-avni-document-readiness-guide',
			'guy-avni-time-management-for-legal-work',
			'guy-avni-process-improvement-for-legal-teams',
		],
		firstH2: 'תיק מסודר מקצר כל שלב בהמשך',
		topicLexicon: [
			'תיק',
			'תיקייה',
			'מבנה',
			'גרסה',
			'משימה',
			'מעקב',
			'צוות',
			'תיוג',
			'חיפוש',
			'ארכיון',
			'סדר',
			'זרימה',
		],
		sectionBlueprints: [
			{ heading: 'מבנה תיקיות', focus: 'מגדירים עץ אחיד לכל תיק.' },
			{ heading: 'שמות ותיוג', focus: 'משתמשים בשם שמאפשר חיפוש.' },
			{ heading: 'ניהול גרסאות', focus: 'מסמנים טיוטה מול סופי.' },
			{ heading: 'מעקב משימות', focus: 'קושרים משימות למסמכים.' },
			{ heading: 'העברה בין עורכים', focus: 'מסבירים מבנה לעמית.' },
			{ heading: 'סגירת תיק', focus: 'מעבירים לארכיון בצורה אחידה.' },
		],
	}),
	'guy-avni-time-management-for-legal-work': spec('guy-avni-time-management-for-legal-work', {
		title: 'גיא אבני עו״ד | ניהול זמן בעבודה משפטית עמוסה',
		description: 'ניהול זמן: עדיפויות, חסימות זמן ומניעת שריפת צוות.',
		metaTitle: 'גיא אבני עו״ד | ניהול זמן בעבודה משפטית עמוסה',
		metaDescription:
			'גיא אבני עו״ד מציג ניהול זמן בעבודה משפטית: עדיפויות, חסימות זמן, מעקב עומס ומניעת שחיקה. מדריך מעשי לעורכי דין.',
		mainKeyword: 'גיא אבני עו״ד',
		category: 'operations',
		tags: ['time', 'focus', 'operations'],
		relatedBlogSlugs: [
			'guy-avni-process-improvement-for-legal-teams',
			'guy-avni-meeting-preparation-checklist',
			'guy-avni-positive-case-organization',
			'guy-avni-service-quality-standards',
		],
		firstH2: 'ניהול זמן הוא ניהול עדיפויות ולא רשימת משימות',
		topicLexicon: [
			'זמן',
			'עדיפות',
			'מיקוד',
			'לוח',
			'עומס',
			'הפרעה',
			'דדליין',
			'חסימה',
			'צוות',
			'שחיקה',
			'מדידה',
			'שגרה',
		],
		sectionBlueprints: [
			{ heading: 'דירוג עדיפויות', focus: 'מפרידים דחוף מחשוב.' },
			{ heading: 'חסימות זמן', focus: 'שומרים זמן לעבודה עמוקה.' },
			{ heading: 'ניהול פגישות', focus: 'מצמצמים פגישות מיותרות.' },
			{ heading: 'מעקב עומס', focus: 'מזהים עומס יתר מוקדם.' },
			{ heading: 'הפקת לקחים', focus: 'בודקים מה בלע זמן.' },
			{ heading: 'איזון עבודה-חיים', focus: 'שומרים על קצב בר-קיימא.' },
		],
	}),
	'guy-avni-collaboration-with-external-experts': spec('guy-avni-collaboration-with-external-experts', {
		title: 'גיא אבני | שיתוף פעולה עם מומחים חיצוניים בתיק משפטי',
		description: 'שיתוף עם מומחים: בחירה, חוזה, תיאום ותיעוד תוצרים.',
		metaTitle: 'גיא אבני | שיתוף פעולה עם מומחים חיצוניים בתיק',
		metaDescription:
			'גיא אבני מסביר שיתוף עם מומחים חיצוניים: בחירה, הסכם, תיאום ציפיות ותיעוד תוצרים בתיק משפטי. מדריך לניהול תיקים מורכבים.',
		mainKeyword: 'גיא אבני',
		category: 'operations',
		tags: ['collaboration', 'experts', 'workflow'],
		relatedBlogSlugs: [
			'guy-avni-dispute-prevention-method',
			'guy-avni-evidence-prioritization-framework',
			'guy-avni-contract-review-flow',
			'guy-avni-process-improvement-for-legal-teams',
		],
		firstH2: 'מומחים חיצוניים מחזקים תיק כשיש תיאום נכון',
		topicLexicon: [
			'מומחה',
			'חוות דעת',
			'תיאום',
			'חוזה',
			'תקציב',
			'מועד',
			'תיעוד',
			'תיק',
			'עורך דין',
			'בדיקה',
			'איכות',
			'תקשורת',
		],
		sectionBlueprints: [
			{ heading: 'בחירת מומחה', focus: 'בודקים ניסיון ורלוונטיות.' },
			{ heading: 'הסכם עם מומחה', focus: 'מגדירים היקף ותשלום.' },
			{ heading: 'תיאום ציפיות', focus: 'מסבירים מה נדרש בפלט.' },
			{ heading: 'שילוב בתיק', focus: 'מחברים חוות דעת לטענה.' },
			{ heading: 'בקרת איכות', focus: 'בודקים לפני הגשה.' },
			{ heading: 'תיעוד עלויות', focus: 'שומרים חשבוניות מסודרות.' },
		],
	}),
	'guy-avni-negotiation-clarity-principles': spec('guy-avni-negotiation-clarity-principles', {
		title: 'גיא אבני עורך דין | עקרונות בהירות במשא ומתן משפטי',
		description: 'בהירות במשא ומתן: מטרות, גבולות, ניסוח וסיכום ביניים.',
		metaTitle: 'גיא אבני עורך דין | עקרונות בהירות במשא ומתן משפטי',
		metaDescription:
			'גיא אבני עורך דין מציג עקרונות בהירות במשא ומתן: מטרות, גבולות, ניסוח מדויק וסיכום ביניים. מדריך לעסקים ולצוותים.',
		mainKeyword: 'גיא אבני עורך דין',
		category: 'communication',
		tags: ['negotiation', 'clarity', 'communication'],
		relatedBlogSlugs: [
			'guy-avni-dispute-prevention-method',
			'guy-avni-contract-review-flow',
			'guy-avni-communication-strategy-for-clients',
			'guy-avni-legal-content-writing-approach',
		],
		firstH2: 'משא ומתן מצליח כשהצדדים מבינים את אותה שפה',
		topicLexicon: [
			'משא ומתן',
			'בהירות',
			'מטרה',
			'גבול',
			'הצעה',
			'ניסוח',
			'סיכום',
			'חלופה',
			'לחץ',
			'אמון',
			'חוזה',
			'פתרון',
		],
		sectionBlueprints: [
			{ heading: 'הגדרת מטרות', focus: 'מפרידים בין רצוי למינימום.' },
			{ heading: 'גבולות ברורים', focus: 'מציינים מה לא ניתן למסור.' },
			{ heading: 'ניסוח מדויק', focus: 'נמנעים מעמימות בהצעות.' },
			{ heading: 'סיכום ביניים', focus: 'מתעדים מה הוסכם.' },
			{ heading: 'ניהול לחץ', focus: 'לא חותמים בלי בדיקה.' },
			{ heading: 'סגירה לכתב', focus: 'מסיימים בנוסח חתום.' },
		],
	}),
};

export const ALL_SLUGS = Object.keys(ARTICLE_SPECS);
