/** English slug → Hebrew display (URLs stay English). */
export const TAG_LABELS: Record<string, string> = {
	accident: 'תאונות',
	'additional-tax': 'מס יסף',
	administrative: 'משפט מינהלי',
	analysis: 'ניתוח',
	appraisal: 'שמאות',
	appeal: 'ערעור',
	bank: 'בנקאות',
	'bank-refuses': 'סירוב בנק למשכנתא',
	bankruptcy: 'פשיטת רגל',
	benefits: 'קצבאות והטבות',
	'betterment-levy': 'היטל השבחה',
	billing: 'חיוב וגבייה',
	breach: 'הפרת חוזה',
	building: 'בנייה',
	business: 'עסקים',
	buyer: 'רוכש',
	'buyer-rights': 'זכויות רוכש',
	cancellation: 'ביטול עסקה',
	'car-insurance': 'ביטוח רכב',
	'capital-gains': 'מס שבח',
	'capital-loss': 'הפסד הון',
	case: 'תיקים',
	'case-search': 'חיפוש תיק',
	checks: 'שיקים',
	'child-support': 'מזונות ילדים',
	choosing: 'בחירה',
	'choosing-lawyer': 'בחירת עורך דין',
	claims: 'תביעות',
	clarity: 'בהירות',
	'class-action': 'תביעה ייצוגית',
	clients: 'לקוחות',
	closure: 'סגירת תיק',
	collaboration: 'שיתוף פעולה',
	collection: 'גבייה',
	committee: 'ועד בית',
	communication: 'תקשורת',
	'combination-agreement': 'הסכם קומבינציה',
	combination: 'קומבינציה',
	companies: 'חברות',
	complaint: 'תלונה',
	compliance: 'תאימות',
	construction: 'בנייה וקבלנות',
	'construction-contract': 'חוזה קבלנות',
	consumer: 'צרכנות',
	contractor: 'קבלן',
	content: 'תוכן',
	contracts: 'חוזים',
	costs: 'הוצאות משפט',
	cost: 'עלות',
	courts: 'בתי משפט',
	criminal: 'פלילי',
	damages: 'נזקים',
	deadline: 'מועדים',
	debt: 'חובות',
	decisions: 'החלטות',
	defamation: 'לשון הרע',
	defect: 'ליקוי',
	defects: 'ליקויי בנייה',
	deposit: 'פיקדון',
	dispute: 'סכסוך',
	disputes: 'מחלוקות',
	divorce: 'גירושין',
	'divorce-apartment': 'מכירת דירה בגירושין',
	documents: 'מסמכים',
	driving: 'נהיגה',
	employment: 'דיני עבודה',
	enforcement: 'הוצאה לפועל',
	ethics: 'אתיקה',
	eviction: 'פינוי שוכר',
	evidence: 'ראיות',
	'exempt-dealer': 'עוסק פטור',
	expert: 'מומחים',
	experts: 'מומחים',
	family: 'דיני משפחה',
	fees: 'שכר טרחה',
	'first-apartment': 'דירה ראשונה',
	focus: 'מיקוד',
	growth: 'צמיחה',
	guarantee: 'ערבות חוק מכר',
	habits: 'הרגלים',
	harassment: 'הטרדה',
	'health-insurance': 'ביטוח בריאות',
	income: 'הכנסה',
	inheritance: 'ירושה',
	'inheritance-order': 'צו ירושה',
	increase: 'העלאה',
	insolvency: 'חדלות פירעון',
	installments: 'פריסת תשלומים',
	insurance: 'ביטוח',
	'israel-bar': 'לשכת עורכי הדין',
	'israel-law': 'דין ישראלי',
	land: 'מגרשים',
	legal: 'משפט',
	'land-registry': 'רשם המקרקעין',
	law: 'דין',
	'law-firms': 'משרדי עורכי דין',
	lawyer: 'עורך דין',
	lease: 'שכירות',
	liability: 'אחריות',
	license: 'רישוי',
	liens: 'שעבודים',
	limits: 'הגבלות',
	'linear-tax': 'מס לינארי',
	litigation: 'ליטיגציה',
	'long-term': 'טווח ארוך',
	malpractice: 'רשלנות רפואית',
	marriage: 'נישואין',
	maternity: 'חופשת לידה',
	mediation: 'גישור',
	medical: 'רפואי',
	meetings: 'פגישות',
	mortgage: 'משכנתא',
	'national-insurance': 'ביטוח לאומי',
	negotiation: 'משא ומתן',
	'non-compete': 'אי תחרות',
	notice: 'הודעה מוקדמת',
	onboarding: 'קליטה',
	operations: 'תפעול',
	organization: 'ארגון',
	partnership: 'שותפות',
	payments: 'תשלומים',
	penalty: 'קנס',
	permits: 'היתרים',
	planning: 'תכנון',
	portability: 'גרירת משכנתא',
	'power-of-attorney': 'ייפוי כוח',
	prenup: 'הסכם ממון',
	'pre-approval': 'אישור עקרוני',
	preparation: 'הכנה',
	prevention: 'מניעה',
	priority: 'תעדוף',
	process: 'תהליכים',
	product: 'מוצר',
	professionalism: 'מקצועיות',
	'purchase-tax': 'מס רכישה',
	purchase: 'רכישה',
	quality: 'איכות',
	ranking: 'דירוג',
	readiness: 'מוכנות',
	'real-estate': 'נדל״ן',
	'real-estate-law': 'דיני נדל״ן',
	record: 'רישום פלילי',
	recovery: 'שיקום חדלות פירעון',
	'red-flags': 'דגלים אדומים',
	refinance: 'מחזור משכנתא',
	refund: 'החזר כספי',
	registration: 'רישום',
	reporting: 'דיווח למס',
	registry: 'מרשם',
	rent: 'שכירות',
	'rental-income': 'הכנסה משכירות',
	rental: 'שכירות',
	'rent-increase': 'העלאת שכר דירה',
	retainer: 'מקדמה',
	review: 'בדיקה',
	rights: 'זכויות',
	risk: 'סיכונים',
	routine: 'שגרה',
	sealing: 'חיסוי',
	'sale-agreement': 'הסכם מכר',
	'sale-law': 'חוק המכר',
	'sale-transaction': 'עסקת מכר',
	'second-apartment': 'דירה שנייה',
	'self-representation': 'ייצוג עצמי',
	service: 'שירות',
	settlement: 'פשרה',
	'shared-building': 'בית משותף',
	signature: 'חתימה',
	'single-apartment': 'דירה יחידה',
	'undeclared-apartment': 'מכירת דירה לא מדווחת',
	'small-claims': 'תביעות קטנות',
	statute: 'התיישנות',
	strategy: 'אסטרטגיה',
	tabu: 'טאבו',
	tama38: 'תמא 38',
	tax: 'מיסים',
	'tax-authority': 'רשות המסים',
	'tenant-rights': 'זכויות שוכר',
	termination: 'סיום העסקה',
	'third-party': 'צד ג׳',
	time: 'ניהול זמן',
	timeline: 'לוחות זמנים',
	'travel-ban': 'עיכוב יציאה',
	trust: 'אמון',
	'unprotected-lease': 'שכירות בלתי מוגנת',
	'urban-renewal': 'התחדשות עירונית',
	urgent: 'דחוף',
	vat: 'מע״מ',
	wages: 'שכר',
	workflow: 'זרימת עבודה',
	writing: 'כתיבה',
};

export const CATEGORY_LABELS: Record<string, string> = {
	benefits: 'קצבאות והטבות',
	business: 'עסקים',
	communication: 'תקשורת',
	consumer: 'צרכנות',
	contracts: 'חוזים',
	criminal: 'פלילי',
	documents: 'מסמכים',
	employment: 'דיני עבודה',
	family: 'דיני משפחה',
	insurance: 'ביטוח',
	litigation: 'ליטיגציה',
	medical: 'רפואי',
	operations: 'תפעול ארגוני',
	'real-estate': 'נדל״ן',
	'real-estate-law': 'דיני נדל״ן',
	service: 'שירות',
	strategy: 'אסטרטגיה',
	tax: 'מיסים',
	traffic: 'תעבורה',
};

export function getTagLabel(slug: string): string {
	const label = TAG_LABELS[slug];
	if (!label) {
		console.error('[taxonomy-labels] missing TAG_LABELS entry', { slug });
		return slug;
	}
	return label;
}

export function getCategoryLabel(slug: string): string {
	const label = CATEGORY_LABELS[slug];
	if (!label) {
		console.error('[taxonomy-labels] missing CATEGORY_LABELS entry', { slug });
		return slug;
	}
	return label;
}

/** Meta description for /tags/[slug]/ - 14–18 words including multiword Hebrew label. */
export function buildTagMetaDescription(hebrewLabel: string): string {
	return `תכנים בעברית על ${hebrewLabel}, כלים מעשיים ליישום מיידי, ניווט נוח למאמרים נוספים ולעמוד יצירת קשר.`;
}

/** Document title for tag listing page (creative, includes brand). */
export function buildTagPageTitle(hebrewLabel: string): string {
	return `גיא אבני עו״ד | תגית: ${hebrewLabel}`;
}

/** Meta description for /categories/[slug]/ */
export function buildCategoryMetaDescription(hebrewLabel: string): string {
	return `מאמרים בעברית תחת תחום ${hebrewLabel}, דגשים פרקטיים, קישורים למאמרים ותגיות, ומסלול מהיר לפגישה ראשונה.`;
}

export function buildCategoryPageTitle(hebrewLabel: string): string {
	return `אבני גיא | קטגוריה: ${hebrewLabel}`;
}
